steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', 'f', 'train_local_project.dockerfile', '-t', 'gcr.io/projectmlops-374817/train_project_2:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/projectmlops-374817/train_project_2']
