# config_cpu.yaml
workerPoolSpecs:
   machineSpec:
      machineType: n1-highmem-2
   replicaCount: 1
   containerSpec:
      imageUri: gcr.io/dtumlops-374515/project_train:latest
      env:
         - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
           value: python
