name: "Run isort"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python 3.10.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.8
        cache: 'pip'
    - name: run isort
      run: |
        pip install isort==4.3.20
        isort -c -v .
